---

- hosts: k3s_cluster
  become: yes

  pre_tasks:
    - name: Activating cgroup support
      lineinfile:
        path: /boot/cmdline.txt
        regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
        backrefs: true
      notify: reboot
  
  roles:
    - k3s/common
  
  handlers:
    - name: reboot
      reboot:

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - k3s/master

- hosts: node
  become: yes
  roles: 
    - k3s/node
